extends Node

var first_names = ["Aaron", "Adam", "Alan", "Albert", "Antonio", "Arthur", "Benjamin", "Bill", "Billy", "Bob", "Bobby", "Brandon", "Brian", "Bruce", "Caleb", "Carl", "Carlos", "Chad", "Chris", "Clarence", "Clint", "Craig", "Dave", "Earl", "Ernest", "Eugene", "Fred", "Gary", "Gerald", "Greg", "Harry", "Henry", "Howard", "Jack", "Jeff", "Jeremy", "Jesse", "Jim", "Jimmy", "Joe", "John", "Johnny", "Jonathan", "Josh", "Juan", "Justin", "Keith", "Kevin", "Larry", "Lawrence", "Louis", "Mark", "Martin", "Mike", "Nicholas", "Paul", "Phillip", "Ralph", "Randy", "Roger", "Ron", "Roy", "Russell", "Ryan", "Samuel", "Scott", "Sean", "Shawn", "Steve", "Terry", "Tim", "Todd", "Tom", "Victor", "Wayne", "Willie", "Zachary"]
var last_names = ["Smith", "Jones", "Williams", "Brown", "Davis", "Miller", "Wilson", "Moore", "Taylor", "Anderson", "Thomas", "Jackson", "White", "Harris", "Martin", "Thompson", "Garcia", "Martinez", "Robinson", "Clark", "Rodriguez", "Lewis", "Lee", "Walker", "Hall", "Allen", "Young", "Hernandez", "King", "Wright", "Lopez", "Hill", "Scott", "Green", "Adams", "Baker", "Gonzalez", "Nelson", "Carter", "Mitchell", "Perez", "Roberts", "Turner", "Phillips", "Campbell", "Parker", "Evans", "Edwards", "Collins", "Stewart", "Sanchez", "Morris", "Rogers", "Reed", "Cook", "Morgan", "Bell", "Murphy", "Bailey", "Rivera", "Cooper", "Richardson", "Cox", "Howard", "Ward", "Torres", "Peterson", "Gray", "Ramirez", "James", "Watson", "Brooks", "Kelly", "Sanders", "Price", "Bennett", "Wood", "Barnes", "Ross", "Henderson", "Coleman", "Jenkins", "Perry", "Powell", "Long", "Patterson", "Hughes", "Flores", "Washington", "Butler", "Simmons", "Foster", "Gonzales", "Bryant", "Alexander", "Russell", "Griffin", "Diaz", "Hayes", "Myers", "Ford", "Hamilton", "Graham", "Sullivan", "Wallace", "Woods", "Cole", "West", "Jordan", "Owens", "Reynolds", "Fisher", "Ellis", "Harrison", "Gibson", "Mcdonald", "Cruz", "Marshall", "Ortiz", "Gomez", "Murray", "Freeman", "Wells", "Webb", "Simpson", "Stevens", "Tucker", "Porter", "Hunter", "Hicks", "Crawford", "Henry", "Boyd", "Mason", "Morales", "Kennedy", "Warren", "Dixon", "Ramos", "Reyes", "Burns", "Gordon", "Shaw", "Holmes", "Rice", "Robertson", "Hunt", "Black", "Daniels", "Palmer", "Mills", "Nichols", "Grant", "Knight", "Ferguson", "Rose", "Stone", "Hawkins", "Dunn", "Perkins", "Hudson", "Spencer", "Gardner", "Stephens", "Payne", "Pierce", "Berry", "Matthews", "Arnold", "Wagner", "Willis", "Ray", "Watkins", "Olson", "Carroll", "Duncan", "Snyder", "Hart", "Cunningham", "Bradley", "Lane", "Andrews", "Ruiz", "Harper", "Fox", "Riley", "Armstrong", "Carpenter", "Weaver", "Greene", "Lawrence", "Elliott", "Chavez", "Sims", "Austin", "Peters", "Kelley", "Franklin", "Lawson", "Fields", "Gutierrez", "Ryan", "Schmidt", "Carr", "Vasquez", "Castillo", "Wheeler", "Chapman", "Oliver", "Montgomery", "Richards", "Williamson", "Johnston", "Banks", "Meyer", "Bishop", "McCoy", "Howell", "Alvarez", "Morrison", "Hansen", "Fernandez", "Garza"]

func generate_name() -> String:
    var random = RandomNumberGenerator.new()
    random.randomize()
    var first_name_index = random.randi_range(0, first_names.size() - 1)
    var last_name_index = random.randi_range(0, last_names.size() - 1)
    return first_names[first_name_index] + " " + last_names[last_name_index]
